## Initialization
# Clear environment
rm(list = ls())
# Load required packages
library(ape)
library(phangorn)
library(tidytree)
library(treeio)
library(Biostrings)
library(msa)
library(ggtree)
library(ggmsa)
library(jsonlite)
library(tidyverse)
library(ggpubr)
library(aplot)
# if (require(showtext)) {
#   showtext_auto()
#   if (interactive())
#     showtext_opts(dpi = 100)
#   else
#     showtext_opts(dpi = 300)
# }

set.seed(100) # set for reproducibility

## Input
if (interactive()) {
  setwd("/project2/noujdine_61/kdeweese/latissima/corteva_genome")
  line_args <- c(
    "busco_summaries/stramenopiles_odb12.2",
    # "busco_summaries/eukaryota_odb12.2",
    "s-latissima-genome-v2/genomes_metadata.tsv",
    "s-latissima-genome-v2/"
  )
} else if (length(commandArgs(trailingOnly = T)) == 3) {
  line_args <- commandArgs(trailingOnly = T)
} else {
  stop("3 positional arguments expected.")
}
wd <- line_args[1]
in_tsv <- line_args[2]
outdir <- line_args[3]
quast_script <- "quast.R"
# Split lineage from working directory
lineage <- unlist(strsplit(wd, "/"))[2]
# HMM directory in local BUSCO downloads
hmms_dir <- paste("busco_downloads/lineages", lineage, "hmms", sep = "/")
out_grp <- "ectocarpus_liu2024" # outgroup: Ectocarpus
# BUSCO types for figure legend
busco_type <- c(
  "C" = "Complete",
  "S" = "Complete and single-copy",
  "D" = "Complete and duplicated",
  "F" = "Fragmented",
  "M" = "Missing"
)
busco_type_rev <- names(busco_type)
names(busco_type_rev) <- unname(busco_type)
color_names <- unname(busco_type[2:5])
# Order for label factor
lbl_order <- c(
  "latissima.*US",
  "latissima.*France",
  "^(?!.*(US|France)).*latissima",
  "^(?!.*latissima)"
)
# Order for region factor
rg_order <- c("US", "France", "Norway", "Other")

## Output
busc_plot_file <- paste0("busco_", lineage, ".png")
# Prepend output directory to script and plot filenames (if it exists)
if (dir.exists(outdir)) {
  quast_script <- paste(outdir, quast_script, sep = "/")
  busc_plot_file <- paste0(outdir, busc_plot_file)
}

## Functions
# Format species Latin name
formatSpc <- function(spc) {
  spc_f <- gsub("_", " ", spc)
  if (!grepl("Ecto", spc_f)) {
    genus <- word(spc_f, 1, 1)
    species <- word(spc_f, 2, 2)
    genus_abv <- paste0(substr(genus, 1, 1), ".")
    spc_f <- paste(genus_abv, species)
  }
  return(spc_f)
}
# Find JSON summary files for each assembly generated by BUSCO
getBuscoJsons <- function(genome_tab) {
  busc_ids <- pull(genome_tab, BUSCO_id, Label)
  ptn <- paste0(busc_ids, "$")
  ptns <- paste(ptn, collapse = "|")
  busc_res_dirs <- list.files(pattern = ptns)
  busc_res_dirs <- sapply(busc_ids, grep, busc_res_dirs, value = T)
  busc_df <-
    tibble(dir = busc_res_dirs, Label = names(busc_res_dirs))
  busc_json_files <- busc_df %>%
    rowwise() %>%
    filter(dir.exists(dir)) %>%
    mutate(json_files = list.files(
      path = dir,
      pattern = "sho.*\\.json",
      full.names = T
    )) %>%
    ungroup() %>%
    pull(json_files, Label)
  return(busc_json_files)
}
# Parse BUSCO summary JSON file
parseBusco <- function(busc_json_file) {
  busc_data <- read_json(busc_json_file, simplifyVector = T)
  busc_res <- busc_data$results %>%
    unlist() %>%
    as_tibble(rownames = "stat") %>%
    mutate(
      stat = gsub("Single copy", "Complete and single-copy", stat),
      stat = gsub("Multi copy", "Complete and duplicated", stat)
    )
  return(busc_res)
}

## Data wrangling
# sourced <- T
# # Source QUAST output parsing R script
# print(paste("Sourcing", quast_script))
# source(quast_script)
# Set plot colors from base BUSCO plotting function
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
my_colors <- setNames(my_colors, color_names)
# Read table of assembly labels and FASTA file names
genome_tab <- read_tsv(in_tsv, col_names = F, comment = "#")
genome_tab <- genome_tab %>%
  rename(Label = X1, Pretty_Label = X2) %>%
  mutate(
    BUSCO_id = paste(Label, lineage, sep = "_"), # match labels to BUSCO
    # Assembly = paste0("assemblies/", Label, ".fa")
  )
# Sort "Pretty_Label" column with factor for plotting
lbl_lvls <- sapply(regex(lbl_order),
                   grep,
                   unique(genome_tab$Pretty_Label),
                   value = T,
                   perl = T) %>%
  unname() %>%
  unlist()
# Factor "Pretty_Label"
genome_tab <- genome_tab %>%
  mutate(Pretty_Label = factor(Pretty_Label, levels = rev(lbl_lvls)))
# Sort "Label" column based on "Pretty_Label"
lbl_vls_2 <- genome_tab %>%
  arrange(Pretty_Label) %>%
  pull(Label)
genome_tab <- genome_tab %>%
  mutate(
    # Mark polished and draft assemblies
    AssemblyType = case_when(
      grepl("polish", Pretty_Label) ~ ".p",
      grepl("draft", Pretty_Label) ~ ".d",
      .default = ""
    ),
    # Get region from assembly labels
    Region = case_when(
      grepl("US", Pretty_Label, ignore.case = F) ~ "US",
      grepl("France", Pretty_Label, ignore.case = F) ~ "France",
      grepl("Norway", Pretty_Label, ignore.case = F) ~ "Norway",
      .default = "Other"
    ),
    Region = factor(Region, levels = rg_order),
    .after = Label
  ) %>%
  rowwise() %>%
  mutate(
    # Get version from assembly labels
    Version = case_when(
      # Get vN
      grepl("v[0-9]", Pretty_Label) ~ gsub("^.*(v[0-9]).*$", "\\1", Pretty_Label),
      # Get year of cited publication
      grepl("et al\\.", Pretty_Label) ~
        gsub("^.*et al\\.\\ ([0-9]+)\\).*$", "\\1", Pretty_Label),
      .default = "none"
    ),
    Version = paste0(Version, AssemblyType),
    Species = gsub(" \\(.*$", "", Pretty_Label),
    Species = formatSpc(Species),
    .after = Label
  ) %>%
  ungroup()

# Read in BUSCO summaries
busc_json_files <- getBuscoJsons(genome_tab)
busc_res <- sapply(busc_json_files, parseBusco, simplify = F)
busc_res <- busc_res %>%
  bind_rows(.id = "Label") %>%
  left_join(genome_tab, .) %>%
  # Factor "Label"
  mutate(Label = factor(Label, levels = lbl_vls_2))
busc_res_filt <- busc_res %>%
  # Keep only BUSCO gene reporting and convert values to numbers
  filter(grepl(paste(busco_type, collapse = "|"), stat)) %>%
  mutate(value = as.numeric(value)) %>%
  # Separate gene counts and percentages into two columns
  separate_wider_regex(stat,
                       patterns = c(Category = ".*", "\\s",
                                    Value_Type = "per.*|BUS.*")) %>% 
  pivot_wider(names_from = Value_Type, values_from = value) %>%
  # Create one-line summary labels for each assembly
  mutate(
    C = busco_type_rev[Category],
    Summary = paste(C, BUSCOs, sep = ":"),
    Summary = case_when(
      C == "S" ~ paste0("[", Summary),
      C == "D" ~ paste0(Summary, "]"),
      .default = Summary
    )
  ) %>%
  group_by(Label) %>%
  mutate(Summary = case_when(C == "S" ~ paste(Summary, collapse = ", ")),
         Summary = gsub(", \\[", " \\[", Summary)) %>%
  ungroup() %>%
  # Sort BUSCO result categories by desired order in bars
  mutate(Category = factor(Category, levels = unname(busco_type))) %>%
  # Remove "Complete" category (already represented by "S" and "D")
  filter(Category != "Complete")

# df2 <- quast_df %>%
#   rowwise() %>%
#   # Convert Label to factor ordered by tree tip labels
#   mutate(
#     Label_real = gsub(" ", "_", Label),
#     Label_real = names(unlist(sapply(tip.label(tp), grep, Label_real,
#                                        value = T))),
#     Label_real = factor(Label_real, levels = tip.label(tp))
#   ) %>%
#   ungroup() %>%
#   arrange(Label_real) %>%
#   mutate(Label = factor(Label, levels = unique(Label))) %>%
#   # Pivot wider for plot
#   pivot_wider(id_cols = Label,
#               names_from = Stat,
#               values_from = Assembly)

len_stat_cols <- c("length", "scaffold", "contig", "gap")
len_df <- busc_res %>%
  filter(grepl(paste(len_stat_cols, collapse = "|"), stat, ignore.case = T)) %>%
  mutate(value = as.numeric(gsub("%", "", value)))

# Format plot titles and axis labels
total_buscos <- busc_res %>%
  filter(stat == "n_markers") %>%
  pull(value) %>%
  unique()
lin_split <- unlist(strsplit(lineage, "_"))
lin <- tools::toTitleCase(lin_split[1])
odb_v <- toupper(lin_split[2])
x_lab1 <- paste(lin, odb_v, "BUSCOs")
x_lab2 <- paste0("(n = ", total_buscos, ")")
x_lab <- paste(x_lab1, x_lab2)

# Plotting
# Get dictionary for plot labels
lbl_dict <- genome_tab %>%
  mutate(Plot_Label = paste(Species, Version)) %>%
  pull(Plot_Label, Label)
# Bar plot of BUSCO score breakdown
busc_plot <- ggplot(data = busc_res_filt,
                    mapping = aes(x = percentage, y = Label)) +
  geom_col(mapping = aes(fill = Category),
           position = position_stack(reverse = T),
           width = 0.8) +
  geom_text(mapping = aes(label = Summary), x = 5, hjust = 0, na.rm = T) +
  scale_fill_manual(name = NULL, values = my_colors,
                    labels = scales::label_wrap(width = 15)) +
  guides(fill = guide_legend(ncol = 2, position = "top")) +
  facet_grid(rows = vars(Region), scales = "free", space = "free",
             switch = "both") +
  scale_x_continuous(name = x_lab,
                     labels = scales::label_percent(scale = 1),
                     expand = expansion(mult = 0, add = c(0, 2)),
                     breaks = c(20, 40, 60, 80, 100)) +
  scale_y_discrete(labels = lbl_dict) +
  coord_cartesian(clip = "off") +
  theme_classic2() +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_text(face = "italic"),
        strip.placement = "outside",
        panel.grid.major.x = element_line(color = "grey90"),
        panel.grid.minor.x = element_line(color = "grey90"))
# Save BUSCO plot
print(paste("Saving BUSCO plot to:", busc_plot_file))
ggsave(
  filename = busc_plot_file,
  plot = busc_plot,
  bg = "white",
  width = 9,
  height = 6
)

# Barplot of total length for each species
len_plot <- len_df %>%
  filter(stat == "Total length") %>%
  ggplot(aes(x = value/1e6, y = Label)) +
  geom_col(position = "dodge", fill = "grey", show.legend = F) +
  # scale_x_continuous(labels = scales::label_comma()) +
  scale_y_discrete(labels = lbl_dict) +
  xlab("Total length (Mb)") +
  # facet_wrap(~ stat, scales = "free") +
  theme_classic2() +
  theme(
    axis.title.y = element_blank(),
    # axis.text.y = element_blank()
  ) +
  labs(title = "   ")

# Build tree
# Read in list of all lineage ortholog IDs from HMM directory
og_ids <- sub(
  "\\.hmm$",
  "",
  list.files(path = hmms_dir, pattern = "\\.hmm$")
) %>%
  tibble(OG = .) %>%
  separate_wider_delim(OG, delim = "at", names = c("OG", "Lineage_ID")) %>%
  distinct(OG)
# Construct paths to BUSCO single-copy FASTAs
genome_tab <- genome_tab %>%
  mutate(BUSCO_SC = paste0(
    "busco_results/",
    lineage,
    "/",
    Label,
    "/run_",
    lineage,
    "/busco_sequences/single_copy_busco_sequences"
  ))
n_asm <- length(unique(genome_tab$Label)) # number of assemblies
# Check each BUSCO single-copy result directory exists
for (sc_dir in genome_tab$BUSCO_SC) {
  if (!file.exists(sc_dir)) {
    stop(paste0("BUSCO single-copy seq. directory (", sc_dir, ") not found."))
  }
}
sc_list <- sapply(genome_tab$BUSCO_SC, list.files, pattern = ".faa",
                  full.names = T, simplify = F)
sc_list <- sapply(sc_list, as_tibble_col, column_name = "OG_FAA", simplify = F)
sc_df <- sc_list %>%
  bind_rows(.id = "BUSCO_SC") %>%
  # Join to assembly labels
  left_join(genome_tab) %>%
  select(-BUSCO_SC) %>%
  # Extract BUSCO orthogroup (OG) IDs
  mutate(OG = gsub("\\.faa", "", basename(OG_FAA)), .before = 1) %>%
  mutate(OG = paste0("OG", OG)) %>%
  separate_wider_delim(OG, delim = "at", names = c("OG", "Lineage_ID")) %>%
  # Filter for OG present in all assemblies
  filter(n() == length(genome_tab$Label), .by = OG) %>%
  # Read in predicted protein sequences of each OG from each assembly
  rowwise() %>%
  mutate(Protein_Seq = as.character(readAAStringSet(OG_FAA))) %>%
  ungroup() %>%
  # Save protein IDs separately
  mutate(Protein_ID = names(Protein_Seq),
         Protein_Seq = unname(Protein_Seq)) %>%
  # Strip terminal stop codons (*)
  mutate(Protein_Seq = gsub("\\*$", "", Protein_Seq)) %>%
  # Filter out OGs with internal stop codons
  filter(!any(grepl("\\*", Protein_Seq)), .by = OG) %>%
  # Parse information from protein IDs
  separate_wider_delim(Protein_ID,
                       delim = "|",
                       names = c("OG_Hit", "Hit", "Strand")) %>%
  mutate(Strand = gsub("^.*([+-]).*$", "\\1", Strand)) %>%
  separate_wider_delim(Hit, delim = ":", names = c("Chr", "Coordinates")) %>%
  separate_wider_delim(Coordinates,
                       delim = "-",
                       names = c("Start", "End"))

# Align protein orthologs
n_ogs <- length(unique(sc_df$OG)) # number of present orthogroups
sc_aln <- list()
sc_aa <- list()
for (i in 1:n_ogs) {
  cat(i, "/", n_ogs, "\n")
  og <- unique(sc_df$OG)[[i]]
  prots <- sc_df %>%
    filter(OG == og) %>%
    arrange(Label) %>%
    pull(Protein_Seq, Label) %>%
    AAStringSet()
  aln <- msa(prots, method = "Muscle", type = "protein", order = "input",
             verbose = F)
  sc_aln[[og]] <- aln
  sc_aa[[og]] <- msaConvert(aln, type = "ape::AAbin")
}
# Concatenate all alignments into supermatrix
super <- do.call(cbind, sc_aa)
cat("Alignment supermatrix length:", dim(super)[2], "bp", "\n")
super_phy <- as.phyDat(super) # convert to phyDat object

# Generate assembly phylogeny from single-copy BUSCO protein alignments
# Tree 1: Neighbor-joining (NJ)
cat("Creating neighbor-joining (NJ) tree...", "\n")
dm <- dist.ml(super_phy)
treeNJ <- NJ(dm)
# Root tree to outgroup
treeNJ_r <- root(treeNJ, outgroup = out_grp, resolve.root = T)
# Bootstrap (on unrooted)
cat("Boostrapping NJ tree...", "\n")
bsNJ <- bootstrap.phyDat(super_phy, function(x) NJ(dist.ml(x)))
treeNJ_r_bs <- plotBS(treeNJ_r, bsNJ, main = "NJ + standard bootstrap",
                      type = "none") # get bootstrap node labels
# Plot tree
cat("Plotting NJ tree phylogeny...", "\n")
# Create dictionaries correlating labels and pretty labels
dict_to_pretty <- genome_tab %>%
  distinct(Label, Pretty_Label) %>%
  pull(Pretty_Label, Label)
pNJ <- data.frame(
  node = 1:Nnode(treeNJ_r_bs) + Ntip(treeNJ_r_bs),
  bootstrap = as.numeric(treeNJ_r_bs$node.label) * 100 # add bootstrap as df
) %>%
  full_join(treeNJ_r_bs, ., by = "node") %>%
  ggtree() +
  geom_nodepoint(aes(color = cut(bootstrap, c(0, 70, 90, 100))),
                 shape = 16, size = 2, na.rm = T) +
  geom_tiplab(aes(label = lbl_dict[label] %>%
                    str_replace_all(" \\(", "\n\\(")),
              fontface = "italic",
              align = T) +
  hexpand(0.2) +
  # hexpand(-1) +
  scale_color_manual(values = c("black", "grey", "grey90"),
                     na.value = NA,
                     guide = "legend",
                     name = "Bootstrap (%)",
                     breaks = c('(90,100]', '(70,90]', '(0,70]'),
                     labels = expression(BP >= 90, 70 <= BP * " < 90", BP < 70)) +
  # scale_x_continuous(expand = expansion(mult = 0, add = 0)) +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.15), add = 0)) +
  guides(color = guide_legend(position = "top")) +
  coord_cartesian(clip = "off")
  # theme(legend.position = "top")

# Remake BUSCO plot
busc_plot2 <- ggplot(data = busc_res_filt,
                    mapping = aes(x = percentage, y = Label)) +
  geom_col(mapping = aes(fill = Category),
           position = position_stack(reverse = T),
           width = 0.8) +
  scale_fill_manual(
    name = NULL, values = my_colors,
    labels = scales::label_wrap(width = 15)
  ) +
  guides(fill = guide_legend(nrow = 1, position = "top")) +
  facet_grid(rows = vars(Region),
             # scales = "free",
             # space = "free",
             switch = "both",
             drop = TRUE) +
  scale_x_continuous(name = x_lab,
                     labels = scales::label_percent(scale = 1),
                     expand = expansion(mult = 0, add = c(0, 2)),
                     breaks = c(20, 40, 60, 80, 100)) +
  scale_y_discrete(labels = lbl_dict) +
  coord_cartesian(clip = "off") +
  theme_classic2() +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_text(face = "italic"),
        strip.placement = "inside")

# Modify length plot
len_plot2 <- len_plot +
  facet_grid(rows = vars(Region),
             scales = "free",
             space = "free",
             switch = "both",
             drop = TRUE) +
  theme(axis.text.y = element_blank(),
        strip.text = element_blank(),
        strip.background = element_blank())

# Modify tree plot
pNJ_2 <- pNJ +
  # geom_tiplab(aes(label = label), align = T)
  geom_tiplab(aes(label = lbl_dict[label] %>%
                    str_replace_all(" \\(", "\n\\(")),
              fontface = "italic",
              align = T)
  # hexpand(0.2)
  # vexpand(0.01, direction = -1) +
  # geom_tiplab(aes(label = ""), align = T)

options("aplot_guides" = "keep")
busc_plot2 %>% insert_left(pNJ_2) %>% insert_right(len_plot2)
busc_plot2 %>% insert_right(len_plot2)
ggarrange(pNJ_2,
          busc_plot2 + 
            guides(fill = guide_legend(nrow = 2, position = "top")),
          len_plot2, nrow = 1, widths = c(1, 2, 1))

busco_panel <- busc_res_filt %>%
  transmute(
    Label,
    percentage,
    Category
  )
length_panel <- len_df %>%
  filter(stat == "Total length") %>%
  transmute(
    Label,
    Length_Mb = value * 1e-6
  )
pNJ %>%
  facet_plot(
    panel   = x_lab,
    data    = busco_panel,
    geom    = ggstance::geom_barh,
    mapping = aes(x = percentage, fill = Category),
    position = ggstance::position_stackv(reverse = T),
    stat = 'identity',
    width   = 0.8
  ) %>%
  facet_plot(
    panel   = "Total length (Mb)",
    data    = length_panel,
    geom    = ggstance::geom_barh,
    mapping = aes(x = Length_Mb),
    stat = 'identity',
    fill    = "darkgrey",
    width   = 0.8
  ) +
  scale_fill_manual(values = my_colors) +
  guides(color = guide_legend(order = 1, nrow = 2, position = "top",
                              direction = "vertical"),
         fill = guide_legend(order = 2, nrow = 2, position = "top",
                             direction = "vertical")) +
  theme_tree2() +
  theme(strip.background = element_blank())


# n_plot <- ggplot(data = df2,
#                  mapping = aes(x = `# N's per 100 kbp`,
#                                y = Label)) +
#   geom_col() +
#   scale_x_continuous(label = scales::label_comma(),
#                      expand = expansion(mult = 0, add = c(0, 2))) +
#   coord_cartesian(clip = "off") +
#   theme_classic2() +
#   theme(
#     axis.text.y = element_text(face = "italic", color = "black"),
#     axis.title.y = element_blank(),
#   )
# pp <- ggarrange(
#   n_plot,
#   busc_plot,
#   nrow = 1,
#   widths = c(2, 1),
#   legend = "right",
#   legend.grob = get_legend(busc_plot),
#   align = "h"
# )
# # p <-
# #   ggarrange(tree_plot,
# #             pp,
# #             widths = c(1, 2),
# #             nrow = 1,
# #             align = "h")
# # Save plot with message to user
# print(paste("Saving pretty BUSCO plot of", lineage, "to", busc_plot_file))
# h <- 5
# w <- h * 2.5
# sapply(
#   busc_plot_file,
#   ggsave,
#   plot = pp,
#   bg = "white",
#   width = w,
#   height = h,
#   simplify = F
# )
